# Generated by Django 5.0.4 on 2024-05-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTORY', '0003_remove_employees_quantity_employees_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
